# Generated by Django 3.1 on 2020-08-26 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 21, 24, 38, 517393, tzinfo=utc), verbose_name='дата публикации'),
        ),
    ]
